### ISSUE TITLE
should we move this repo to scalacenter/scala.epfl.ch ?

### ISSUE THREAD

**Issue by SethTisue** [scala/scala.epfl.ch#20]
I feel like people are much likelier to be looking for it there than under scala/

**Comment by heathermiller** [comment]
If it's no major inconvenience to anybody where it is now, I'd rather not to move it, because I'd rather not bother Fabien with the request to mess with the build/deploy machine for this website (I don't have access to the machine that's building and deploying the site so I've got to bug him about it.)

In the repo description on the fork of this repo under the scalacenter organization, I could always just write "THIS REPO IS A FORK OF scala/scala.epfl.ch, please open issues or make PRs there"

It also doesn't hurt to have a repo or two of ours under the scala org, I guess. 

In any case, the reason for it being under the scala org is that the scalacenter org wasn't yet created when we decided we wanted a scala.epfl.ch website (which was even before the Scala Center was idea)
